import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import 'model/Carfact.dart';

class api extends StatefulWidget {
  const api({super.key});

  @override
  State<api> createState() => _apiState();
}

class _apiState extends State<api> {
 Future<Autogenerated>Cat()async{
   var res=await http.get(Uri.parse("https://catfact.ninja/fact"));
   print(res.body);
   print(res.statusCode);
   return Autogenerated.fromJson(jsonDecode(res.body));
 }




  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Api"),
      ),
      body: Column(
        children: [
          FutureBuilder<Autogenerated>
            (future: Cat(),
              builder: (context,snapshot)
              {
              if (snapshot.hasData){
                return Column(
                  children: [
                    Text(snapshot.data!.fact.toString()),
                    Text(snapshot.data!.length.toString())
                  ],
                );
              }
              else if(snapshot.hasError){
                return Text("${snapshot.error}");
              }
              return const CircularProgressIndicator();
              }

          )],
      ),
     );
  }
}
